from .deter_repository import DeterRepository, DeterHistoricalRepository
from .spatial_unit_repository import SpatialUnitRepository
from .spatial_unit_info_repository import SpatialUnitInfoRepository
from .risk_indicators_repository import RiskIndicatorsRepository
from .spatial_unit_dynamic_mapper_factory import SpatialUnitDynamicMapperFactory
from .deter_class_group_repository import DeterClassGroupRepository